-- Socle fourni. N'ajoutez pas de données personnelles ni de mot de passe en clair.
CREATE TABLE events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(60) NOT NULL UNIQUE,
    label varchar(150) NOT NULL,
    event_date date NOT NULL
);
CREATE TABLE schools (id integer PRIMARY KEY, code varchar(30) NOT NULL UNIQUE, label varchar(80) NOT NULL);
CREATE TABLE current_classes (id integer PRIMARY KEY, code varchar(30) NOT NULL UNIQUE, label varchar(80) NOT NULL);
CREATE TABLE entry_levels (id integer PRIMARY KEY, code varchar(40) NOT NULL UNIQUE, label varchar(100) NOT NULL);
CREATE TABLE specialties (id integer PRIMARY KEY, code varchar(50) NOT NULL UNIQUE, label varchar(150) NOT NULL);
CREATE TABLE admins (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username varchar(80) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    active boolean NOT NULL DEFAULT true
);
CREATE TABLE login_rate_limits (
    fingerprint char(64) PRIMARY KEY,
    window_start timestamptz NOT NULL,
    attempts integer NOT NULL
);
-- À faire par le pôle Merise : 003_registrations.sql après validation du MCD/MLD.
