-- 003_registrations.sql
-- Basé sur le MLD du pôle Merise.
-- Tables déjà fournies par le socle (non recréées ici) : events, schools,
-- current_classes, entry_levels, specialties, admins.

-- 1. Conseillers ---------------------------------------------------------
CREATE TABLE advisors (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label varchar(80) NOT NULL UNIQUE
);

INSERT INTO advisors (id, label) VALUES (1, 'Conseiller 1'), (2, 'Conseiller 2');
SELECT setval(pg_get_serial_sequence('advisors','id'), (SELECT max(id) FROM advisors));

-- 2. Créneaux horaires (rendez-vous d'1 h : 9h-12h puis 14h-16h) ---------
CREATE TABLE time_slots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label varchar(30) NOT NULL,
    start_time time NOT NULL UNIQUE,
    end_time time NOT NULL,
    CONSTRAINT time_slots_order CHECK (end_time > start_time),
    CONSTRAINT time_slots_hours CHECK (
        (start_time >= '09:00' AND end_time <= '12:00')
        OR (start_time >= '14:00' AND end_time <= '16:00')
    )
);

INSERT INTO time_slots (id, label, start_time, end_time) VALUES
(1, '09h00 - 10h00', '09:00', '10:00'),
(2, '10h00 - 11h00', '10:00', '11:00'),
(3, '11h00 - 12h00', '11:00', '12:00'),
(4, '14h00 - 15h00', '14:00', '15:00'),
(5, '15h00 - 16h00', '15:00', '16:00');
SELECT setval(pg_get_serial_sequence('time_slots','id'), (SELECT max(id) FROM time_slots));

-- 3. Visiteurs -----------------------------------------------------------
CREATE TABLE visitors (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    last_name varchar(100) NOT NULL,
    first_name varchar(100) NOT NULL,
    birth_date date NOT NULL,
    phone varchar(30) NOT NULL,
    email varchar(254) NOT NULL UNIQUE
);

-- 4. Inscriptions --------------------------------------------------------
CREATE TABLE registrations (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    visitor_id integer NOT NULL REFERENCES visitors(id),
    event_id integer NOT NULL REFERENCES events(id),
    current_class_id integer REFERENCES current_classes(id),
    school_id integer NOT NULL REFERENCES schools(id),
    entry_level_id integer NOT NULL REFERENCES entry_levels(id),
    specialty_id integer REFERENCES specialties(id),
    remark text,
    appointment_date date NOT NULL,
    time_slot_id integer NOT NULL REFERENCES time_slots(id),
    advisor_id integer NOT NULL REFERENCES advisors(id),
    created_at timestamptz NOT NULL DEFAULT now(),
    -- Un conseiller ne peut avoir qu'un visiteur par créneau et par jour
    CONSTRAINT registrations_slot_uq UNIQUE (appointment_date, time_slot_id, advisor_id),
    -- Un visiteur ne s'inscrit qu'une fois par événement
    CONSTRAINT registrations_visitor_event_uq UNIQUE (visitor_id, event_id)
);

CREATE INDEX registrations_event_idx ON registrations (event_id);
CREATE INDEX registrations_school_idx ON registrations (school_id);

-- 5. Vue : créneaux encore disponibles le jour de chaque événement -------
CREATE VIEW available_slots AS
SELECT e.id AS event_id,
       e.event_date AS appointment_date,
       ts.id AS time_slot_id,
       ts.label AS time_slot_label,
       a.id AS advisor_id,
       a.label AS advisor_label
FROM events e
CROSS JOIN time_slots ts
CROSS JOIN advisors a
WHERE NOT EXISTS (
    SELECT 1 FROM registrations r
    WHERE r.appointment_date = e.event_date
      AND r.time_slot_id = ts.id
      AND r.advisor_id = a.id
)
ORDER BY ts.start_time, a.id;